backend:
  datasource:
    url: ${CLEARDB_DATABASE_URL:}
    database: ${CLEARDB_DATABASE_TYPE:}

  messaging:
    url: ${CLOUDAMQP_URL:}
    manageProductsQueue: products.manage.queue
    orderProductsQueue: products.order.queue

endpoints:
  enabled: false
  health:
    enabled: true

spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false