backend:
  datasource:
    serviceId: mysql
    schema: mysql
    database: uasnt
    properties: useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  messaging:
    serviceId: rabbitmq
    manageProductsQueue: products.manage.queue
    orderProductsQueue: products.order.queue
    user: mquser
    password: mquser
    vhost: uasnt