server:
  port: 8888

backend:
  datasource:
    serviceId: mysql
    schema: mysql
    database: uasnt
    properties: useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  messaging:
    serviceId: rabbitmq
    manageProductsQueue: products.manage.queue
    orderProductsQueue: products.order.queue
    user: mquser
    password: mquser
    vhost: uasnt

endpoints:
  enabled: false
  health:
    enabled: true

spring:
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false